# Generated by Django 6.0.2 on 2026-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_grade_term_subject_performancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Base64 encoded QR data', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='QR code image file', null=True, upload_to='qr_codes/'),
        ),
    ]
